name: polymer_dart_examples
version: 0.0.1
author: naotohc <ntaoo.g@gmail.com>
description: |
  PolymerDart Examples
homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  paper_elements: '>=0.4.0 <0.5.0'
  polymer: '>=0.15.0 <0.16.0'
transformers:
- polymer:
    entry_points: web/index.html
